name: Android Production Release

on:
  push:
    branches:
      - develop
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set version code
        run: |
          echo VERSION_CODE=`expr $GITHUB_RUN_NUMBER + 103` >> $GITHUB_ENV

      - name: Clean with Gradle
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew app:assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}
          alias: ${{ secrets.GOOGLE_PLAY_ALIAS }}
          keyStorePassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}
          keyPassword: ${{ secrets.GOOGLE_PLAY_PASSWORD }}

      - name: Publish To App Center
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release')
        uses: wzieba/AppCenter-Github-Action@v1.3.2
        with:
          appName: dahanliordahan-gmail.com/JustEatMission
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: JustEatTesters
          file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          releaseNotes: "${{ github.event.head_commit.message }}"
          notifyTesters: false
          debug: true
